# Generated by Django 5.0 on 2023-12-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_gamehistorymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
