# Generated by Django 5.0 on 2023-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_postmodel_down_votes_alter_postmodel_up_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
