# Generated by Django 4.1.13 on 2023-12-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_postmodel_down_votes_alter_postmodel_up_votes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
