export const USER_REGISTER_REQUEST = "[USER] REGISTER REQUEST";
export const USER_REGISTER_SUCCESS = "[USER] REGISTER SUCCESS";
export const USER_REGISTER_FAILURE = "[USER] REGISTER FAILURE";

export const USER_LOGIN_REQUEST = "[USER] LOGIN REQUEST";
export const USER_LOGIN_SUCCESS = "[USER] LOGIN SUCCESS";
export const USER_LOGIN_FAILURE = "[USER] LOGIN FAILURE";

export const LOGIN_WITH_TOKEN_REQUEST = "[USER] LOGIN WITH TOKEN REQUEST";
export const LOGIN_WITH_TOKEN_SUCCESS = "[USER] LOGIN WITH TOKEN SUCCESS";
export const LOGIN_WITH_TOKEN_FAILURE = "[USER] LOGIN WITH TOKEN FAILURE";

export const USER_LOGOUT = "[USER] LOGOUT";